---
- name: Start and enable Apache (Red Hat)
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Start and enable Apache (Debian)
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Deploy custom index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html

